services:
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    restart: always
    networks:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./front/dist:/usr/share/nginx/html
    command: >
      sh -c "rm -f /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - uvicorn
      - node

  node:
    build: ./front
    container_name: node
    ports:
      - "8080:8080"  # добавляем проброс порта
    env_file:
      - .env
    networks:
      - app
#    volumes:
#      - ./front:/app
    command: npm run dev  # явно указываем команду
    depends_on:
      - uvicorn

  uvicorn:
    build: .
    container_name: uvicorn
    restart: always




    ports: # Добавьте это
      - "8443:8443"  # Проброс порта на хост






    expose:
      - 8443
    env_file:
      - .env
    networks:
      - app
    volumes:
      - ./src:/app/src
    depends_on:
      - redis
      - mysql

  mysql:
    image: mysql:8.0.43
    container_name: mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/core/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
    networks:
      - app
    ports:
      - "3306:3306"

  redis:
    image: redis:7.0-alpine
    restart: always
    expose:
      - ${REDIS_PORT}
    networks:
      - app
    env_file:
      - .env
    environment:
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - redis_data:/data


networks:
  app:
    driver: bridge

volumes:
  mysql_data:
  redis_data: